### ISSUE TITLE
Calling 'depends_on ... => :run' is deprecated! for shopify-graphicsmagick.rb:28

### ISSUE THREAD

**Issue by bbuchalter** [Shopify/homebrew-shopify#104]
```
Brians-MacBook-Pro:~ brianb$ brew install kubectl
Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/shopify-graphicsmagick.rb:28:in `<class:ShopifyGraphicsmagick>'
Please report this to the shopify/shopify tap!
```

Not sure what the best solution for this is, but perhaps we should consider just commenting out [this statement](https://github.com/Shopify/homebrew-shopify/blob/master/shopify-graphicsmagick.rb#L28)?

**Comment by jules2689** [comment]
matched https://github.com/Homebrew/homebrew-core/commit/83a713daeb214e106510366ec40c10e85a8d820a on our master. Closing

**Comment by leo-shopify** [comment]
That was quick :)
