### ISSUE TITLE
broken tap: qt@5.5: unknown version :mountain_lion

### ISSUE THREAD

**Issue by tgwizard** [Shopify/homebrew-shopify#125]
This line specifies an invalid version:

https://github.com/Shopify/homebrew-shopify/blob/c29bd087e801f8b735025e9d5ba9dfe2bdc5e48c/qt%405.5.rb#L26

Current homebrew doesn't support `:mountain_lion` any more: https://github.com/Homebrew/brew/pull/5599

What should we do? I currently cannot run `brew tap shopify/shopify` due to this.

**Comment by Crowl3y** [comment]
Also stuck unable to run `brew tap shopify/shopify` just fyi

**Comment by tgwizard** [comment]
@Crowl3y the issue is now fixed, as of https://github.com/Shopify/homebrew-shopify/pull/126.
