### ISSUE TITLE
Bump ejson to 1.2.1

### ISSUE THREAD

**Issue by clayton-shopify** [Shopify/homebrew-shopify#145]
The ejson formula still references version 1.2.0:

https://github.com/Shopify/homebrew-shopify/blob/9be968e64258fc11fb28afc4cf68216c9455a81b/ejson.rb#L4

 It would be nice to bump it to 1.2.1 to pick up the fix for https://github.com/Shopify/ejson/issues/58.

**Comment by dwradcliffe** [comment]
@burke Any chance you could bump this to the latest version?

**Comment by burke** [comment]
Done.
