### ISSUE TITLE
Add homebrew cask for Vagrant 1.7.4

### ISSUE THREAD

**Issue by mariusbutuc** [Shopify/homebrew-shopify#2]
In the [Vault page with Vagrant installation details](https://vault.shopify.com/vagrant/vagrant-overview#_glossary-of-terms_installation), we're suggesting to use version 1.7.4:

> We've tested up to 1.7.4, which is the required version as of August 30th, 2015.

Opened up a [PR on `homebrew-versions`](https://github.com/caskroom/homebrew-versions/pull/1515), but based on the feedback received there I’m considering adding [it](https://github.com/mariusbutuc/homebrew-versions/blob/aea3942aca09afe842971880e33af6e62121e5e7/Casks/vagrant174.rb) to a personal / custom tap.

@graemej @thegedge @Sirupsen would this be a good home for the cask formula?

**Comment by drdee** [comment]
We are no longer using Vagrant.
