### ISSUE TITLE
 Cannot tap shopify/shopify: invalid syntax in tap!

### ISSUE THREAD

**Issue by vadivelmsc** [Shopify/homebrew-shopify#201]
![image](https://user-images.githubusercontent.com/67764960/102641868-cf099e00-4182-11eb-8676-a52281d17984.png)

**Comment by dagansmith** [comment]
Hi, are you using a Mac M1 here?

**Comment by johndouthat** [comment]
I can't speak for @vadivelmsc, but I have experienced the same error on an M1 Mac

**Comment by vadivelmsc** [comment]
> Hi, are you using a Mac M1 here?

No. But i have resolved it using Linux command in help article

**Comment by dagansmith** [comment]
Same here - I've updated the CLTs as per [this ticket](https://github.com/Shopify/themekit/issues/838)

I then ran terminal under rosetta 2 and installed homebrew which worked fine. 

Then I receive the below error when running `brew tap shopify/shopify
brew install themekit`

`==> Tapping shopify/shopify
Cloning into '/usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify'...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 1154 (delta 26), reused 25 (delta 9), pack-reused 1092
Receiving objects: 100% (1154/1154), 303.12 KiB | 1.22 MiB/s, done.
Resolving deltas: 100% (619/619), done.
Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the shopify/shopify tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/shopify-graphicsmagick.rb:32

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/bazel@10.rb
bazel@10: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the shopify/shopify tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/bazel@10.rb:20

Error: Cannot tap shopify/shopify: invalid syntax in tap!
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "themekit".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
dagan@dagans-MBP ~ % brew tap shopify/shopify
Updating Homebrew...
==> Tapping shopify/shopify
Cloning into '/usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify'...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 1154 (delta 26), reused 25 (delta 9), pack-reused 1092
Receiving objects: 100% (1154/1154), 303.12 KiB | 453.00 KiB/s, done.
Resolving deltas: 100% (619/619), done.
Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the shopify/shopify tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/shopify-graphicsmagick.rb:32

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/bazel@10.rb
bazel@10: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the shopify/shopify tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/bazel@10.rb:20

Error: Cannot tap shopify/shopify: invalid syntax in tap!
dagan@dagans-MBP ~ % brew tap shopify/shopify
brew install themekit
==> Tapping shopify/shopify
Cloning into '/usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify'...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 1154 (delta 26), reused 25 (delta 9), pack-reused 1092
Receiving objects: 100% (1154/1154), 303.12 KiB | 1.31 MiB/s, done.
Resolving deltas: 100% (619/619), done.
Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the shopify/shopify tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/shopify-graphicsmagick.rb:32

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/bazel@10.rb
bazel@10: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the shopify/shopify tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/bazel@10.rb:20

Error: Cannot tap shopify/shopify: invalid syntax in tap!
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "themekit".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.`
