### ISSUE TITLE
Formulas in shopify/shopify aren't accessible from their fully-qualified name after f0d665a31147114fba079520f6948f6c63cec71e

### ISSUE THREAD

**Issue by billycromb** [Shopify/homebrew-shopify#227]
Some details here:
https://discourse.shopify.io/t/homebrew-problems-with-dev-up-in-identity/15393

To reproduce
`brew tap shopify/shopify`
`brew info shopify/shopify/toxiproxy` -- this should find the toxiproxy formula in this tap, but instead it finds nothing. `brew info toxiproxy` does find it. If you manually check out an older commit of homebrew-shopify, it does.

A git bisect blamed https://github.com/Shopify/homebrew-shopify/commit/f0d665a31147114fba079520f6948f6c63cec71e but I really don't understand how that commit could cause this.

```
Billys-MacBook-Pro:homebrew-shopify billycromb$ pwd
/usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify
Billys-MacBook-Pro:homebrew-shopify billycromb$ git checkout f0d665a31147114fba079520f6948f6c63cec71e^
HEAD is now at 664107e Merge pull request #225 from mllemango/bump-shopify-cli-1.8.0
Billys-MacBook-Pro:homebrew-shopify billycromb$ brew info shopify/shopify/toxiproxy
shopify/shopify/toxiproxy: stable 2.1.2
https://github.com/Shopify/toxiproxy
/usr/local/Cellar/toxiproxy/2.1.2 (5 files, 13.4MB) *
  Built from source on 2021-03-30 at 11:37:24
From: https://github.com/shopify/homebrew-shopify/blob/HEAD/toxiproxy.rb
==> Requirements
Required: x86_64 architecture ✔
==> Caveats
To have launchd start shopify/shopify/toxiproxy now and restart at login:
  brew services start shopify/shopify/toxiproxy
Or, if you don't want/need a background service you can just run:
  toxiproxy
Billys-MacBook-Pro:homebrew-shopify billycromb$ git checkout f0d665a31147114fba079520f6948f6c63cec71e
Previous HEAD position was 664107e Merge pull request #225 from mllemango/bump-shopify-cli-1.8.0
HEAD is now at f0d665a Add autoconf 2.69 to the backported packages
Billys-MacBook-Pro:homebrew-shopify billycromb$ brew info shopify/shopify/toxiproxy
Error: No available formula or cask with the name "shopify/shopify/toxiproxy".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
```

@cuducos also ran into this

cc @donk-shopify @byroot

**Comment by donk-shopify** [comment]
I've verified @simonlevasseur's findings. Making a directory called `Formula` and moving any of the formula modules into it causes a similar effect.

**Comment by simonlevasseur** [comment]
This is where Homebrew determines the `formula_dir`: https://github.com/Homebrew/brew/blob/49e5c3cb231ffbff7316fd4762bbdae1858c57f4/Library/Homebrew/tap.rb#L412-L419

It selects the first directory that exists in `[path/"Formula", path/"HomebrewFormula", path]` where `path` is the Git repo root.

That explains why only the autoconf@2.69 formula was available.
